apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry-operator
    control-plane: controller-manager
  name: opentelemetry-operator-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    scheme: https
    scrapeTimeout: 10s
    targetPort: 8443
    tlsConfig:
      ca: {}
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      cert: {}
      serverName: opentelemetry-operator-controller-manager-metrics-service.openshift-opentelemetry-operator.svc
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator
