apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-opentelemetry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/otel-bundle-pull-request.yaml".pathChanged() ||
      ".tekton/otel-bundle-push.yaml".pathChanged() ||
      "Dockerfile.bundle".pathChanged() ||
      "bundle-patch/***".pathChanged() ||
      "opentelemetry-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: otel
    appstudio.openshift.io/component: otel-bundle
    pipelines.appstudio.openshift.io/type: build
  name: otel-bundle-on-push
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/otel/opentelemetry-bundle:{{revision}}
  - name: dockerfile
    value: Dockerfile.bundle
  - name: build-source-image
    value: "true"
  - name: build-args
    value:
      - REGISTRY=registry.stage.redhat.io
    # Do not use hermetic for now as we are going to generate our manifest at build time. We need to pull in content.
  - name: hermetic
    value: "false"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
