apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-opentelemetry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "development" &&
      (".tekton/otel-fbc-v4-14-pull-request.yaml".pathChanged() ||
      ".tekton/otel-fbc-v4-14-push.yaml".pathChanged() ||
      "Dockerfile-v4-14.catalog".pathChanged() ||
      "catalog/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: otel-fbc-v4-14-development
    appstudio.openshift.io/component: otel-fbc-v4-14-development
    pipelines.appstudio.openshift.io/type: build
  name: otel-fbc-v4-14-development-on-push
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/otel/otel-fbc-v4-14:{{revision}}
  - name: dockerfile
    value: Dockerfile-v4-14.catalog
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      #      - linux/x86_64
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
