apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-opentelemetry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudge-files: "bundle-patch/bundle.env"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/otel-target-allocator-pull-request.yaml".pathChanged() ||
      ".tekton/otel-target-allocator-push.yaml".pathChanged() ||
      "Dockerfile.operator".pathChanged() ||
      "rpms.lock.yaml".pathChanged() ||
      "opentelemetry-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: otel-main
    appstudio.openshift.io/component: otel-target-allocator-main
    pipelines.appstudio.openshift.io/type: build
  name: otel-target-allocator-main-on-push
  namespace: rhosdt-tenant
spec:
  taskRunSpecs:
    - pipelineTaskName: prefetch-dependencies
      computeResources:
        requests:
          cpu: 300m
          memory: 256Mi
        limits:
          memory: 4Gi
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./opentelemetry-operator"}, {"type": "rpm"}]'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/otel/opentelemetry-target-allocator:{{revision}}
  - name: dockerfile
    value: Dockerfile.targetallocator
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  - name: snyk-project
    value: otel-target-allocator
  - name: snyk-ignore-file-paths
    value: "redhat-opentelemetry-collector/"
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
