apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
  tasks:
  - name: init
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.4@sha256:c32f8945266f371474e383a8844972e0ad489149e7581e0418523c0f76d2324a
      - name: kind
        value: task
    params:
    - name: enable-cache-proxy
      value: $(params.enable-cache-proxy)
  - name: clone-repository
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:306b69e6db435ad4a7cf258b6219d9b998eb37da44f5e9ac882ac86a08109154
      - name: kind
        value: task
    runAfter:
    - init
    params:
    - name: url
      value: "$(params.git-url)"
    - name: revision
      value: "$(params.revision)"
    - name: ociStorage
      value: "$(params.output-image).git"
    - name: ociArtifactExpiresAfter
      value: "$(params.image-expires-after)"
    workspaces:
    - name: basic-auth
      workspace: git-auth
  - name: prefetch-dependencies
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:9a8b6e28cfc95282e9afe4acaf7b360be4ac69ac143fb74224e43cb536b62257
      - name: kind
        value: task
    params:
    - name: input
      value: "$(params.prefetch-input)"
    - name: hermetic
      value: "$(params.hermetic)"
    - name: dev-package-managers
      value: $(params.prefetch-dev-package-managers-enabled)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
  - name: build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.9@sha256:8ece4568c88f83fb129272634f100bc1ad117e1c3d9c2432b33e00fe2ada3a3b
      - name: kind
        value: task
    runAfter:
    - clone-repository
    params:
    - name: IMAGE
      value: "$(params.output-image)"
    - name: DOCKERFILE
      value: "$(params.dockerfile)"
    - name: CONTEXT
      value: "$(params.path-context)"
    - name: BUILD_ARGS
      value:
      - $(params.build-args[*])
    - name: HERMETIC
      value: "$(params.hermetic)"
    - name: PREFETCH_INPUT
      value: "$(params.prefetch-input)"
    - name: IMAGE_EXPIRES_AFTER
      value: "$(params.image-expires-after)"
    - name: COMMIT_SHA
      value: "$(tasks.clone-repository.results.commit)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: BUILDAH_FORMAT
      value: $(params.buildah-format)
    - name: HTTP_PROXY
      value: $(tasks.init.results.http-proxy)
    - name: NO_PROXY
      value: $(tasks.init.results.no-proxy)
  - name: build-source-image
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: source-build-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.3@sha256:eb620d137d2dfa9966d991ac210ad14f391cfa9cfc501e3cc1eb24e3332c6986
      - name: kind
        value: task
    when:
    - input: "$(params.build-source-image)"
      operator: in
      values:
      - 'true'
    runAfter:
    - build-container
    params:
    - name: BINARY_IMAGE
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: BINARY_IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: deprecated-base-image-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:516ea66977bc4cdad1da61d9273a31540f0d419270f8c8c4b6b3a6aaa4002d96
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: clair-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:1f19b5f4d706b97426f11ac40ffc0a1eeb1a54b37d2c16395799e7456252e7a8
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: rpms-signature-scan
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: rpms-signature-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:8252a4a973942eeff659fb8727f59838592a9a0e1b3212134915e6aed9239b27
      - name: kind
        value: task
      resolver: bundles
  - name: sast-snyk-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sast-snyk-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:c4b79e009cbfe58cdb80775aedd16e7fc7ee5896ec77431584abb36f067c6484
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: ARGS
      value: "--project-name=$(params.snyk-project) --report --org=0eebca54-4fa1-4638-9ac6-f95f789a9d3e"
    - name: IGNORE_FILE_PATHS
      value: $(params.snyk-ignore-file-paths)
  - name: clamav-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:10054cd4e09cdafb2d16526afb9801490104b54ce0b77c70e417fe756b3daaff
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: sast-coverity-check
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: BUILD_ARGS
      value:
      - $(params.build-args[*])
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - coverity-availability-check
    taskRef:
      params:
      - name: name
        value: sast-coverity-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.3@sha256:e8c63570f1d01d70b2a21b22a2a4aad9ca7d5c0327d8b2a4058a6e616cce17ca
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
    - input: $(tasks.coverity-availability-check.results.STATUS)
      operator: in
      values:
      - success
  - name: coverity-availability-check
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: coverity-availability-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-coverity-availability-check:0.2@sha256:c9b9301c442830eca3ad7d9d5287b082b94c38d406442f391447484147afd006
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-shell-check
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: sast-shell-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:a528f0170b0d0de8db53dfdf02b96d201f3d9f735a904c645b5b111cea7ef44f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-unicode-check
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: sast-unicode-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.4@sha256:2bcccabd857914f66543d17a676f4d259daa67fe55c63a7d317000365c369792
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  params:
  - name: git-url
    type: string
    description: Source Repository URL
  - name: revision
    type: string
    description: Revision of the Source Repository
    default: ''
  - name: output-image
    type: string
    description: Fully Qualified Output Image
  - name: path-context
    type: string
    description: Path to the source code of an application's component from where to build image.
    default: "."
  - default: []
    description: Array of --build-arg values ("arg=value" strings) for buildah
    name: build-args
    type: array
  - name: dockerfile
    type: string
    description: Path to the Dockerfile inside the context specified by parameter path-context
    default: Dockerfile
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ''
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Enable dev-package-managers in prefetch task
    name: prefetch-dev-package-managers-enabled
    type: string
  - name: java
    type: string
    description: Java build
    default: 'false'
  - name: image-expires-after
    description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
    default: ''
  - name: build-source-image
    type: string
    description: Build a source image.
    default: 'false'
  - name: snyk-project
    type: string
    description: Snyk project name
    default: 'red-hat-openshift-distributed-tracing'
  - name: snyk-ignore-file-paths
    type: string
    description: Ignore snyk project paths (comma separated)
    default: ""
  - name: buildah-format
    default: docker
    type: string
    description: The format for the resulting image's mediaType. Valid values are oci or docker.
  - name: enable-cache-proxy
    default: 'false'
    description: Enable cache proxy configuration
    type: string
  workspaces:
  - name: git-auth
    optional: true
  results:
  - name: IMAGE_URL
    description: ''
    value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: IMAGE_DIGEST
    description: ''
    value: "$(tasks.build-container.results.IMAGE_DIGEST)"
  - name: CHAINS-GIT_URL
    description: ''
    value: "$(tasks.clone-repository.results.url)"
  - name: CHAINS-GIT_COMMIT
    description: ''
    value: "$(tasks.clone-repository.results.commit)"
  finally:
  - name: show-sbom
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:e119aa864b094715cb8dd01d44d2752658f1a1b83a3417e92456f26a06a3c1d8
      - name: kind
        value: task
    params:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: show-summary
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:3f6e8513cbd70f0416eb6c6f2766973a754778526125ff33d8e3633def917091
      - name: kind
        value: task
    params:
    - name: pipelinerun-name
      value: "$(context.pipelineRun.name)"
    - name: git-url
      value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
    - name: image-url
      value: "$(params.output-image)"
    - name: build-task-status
      value: "$(tasks.build-container.status)"
