name: Update FBC catalog template

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - main
      - development
    paths:
      - 'catalog/**'

jobs:
  update-catalog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: install OPM
        run: |
          wget https://github.com/operator-framework/operator-registry/releases/download/v1.53.0/linux-amd64-opm
          chmod +x linux-amd64-opm

      - name: Log into registry.redhat.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_TOKEN }}

      - name: generate catalog
        run: ./scripts/update-catalog.sh
