name: Generate FBC catalogs

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - main
      - development
    paths:
      - 'catalog/**'

jobs:
  update-catalog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install OPM
        run: |
          wget https://github.com/operator-framework/operator-registry/releases/download/v1.53.0/linux-amd64-opm
          chmod +x linux-amd64-opm
          mkdir .bin
          mv linux-amd64-opm ./.bin/opm
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: Log into registry.redhat.io
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_TOKEN }}

      - name: Generate catalog
        run: ./scripts/update-catalog.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate catalogs
          file_pattern: 'catalog/**'